version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
      args:
        - NODE_ENV=development
    container_name: dividend-notice.net
    ports:
    - "3000:3000"
    command: "npm run dev"
    networks:
      - public
      - private
    depends_on:
      - db

  db:
    build:
      context: ./
      dockerfile: db.Dockerfile
    container_name: db.dividend-notice.net
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      TZ: "Asia/Tokyo"
    networks:
      - private

networks:
  public:
  private:
