version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
      args:
        - NODE_ENV=development
    container_name: dividend-notice.net
    ports:
    - "3000:3000"
    command: "npm run dev"
    networks:
      - public
      - private
    depends_on:
      - db
#    restart: always
  db:
    image: "postgres"
    container_name: db.dividend-notice.net
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - public
#    restart: always

networks:
  public:
  private:
